version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - OPENAI_MODEL=gpt-4o-mini
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    restart: unless-stopped

volumes:
  mongodb_data: 