version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: voice-interview-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:9999
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: voice-interview-backend
    ports:
      - "9999:9999"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=9999
      - NODE_ENV=development
    restart: unless-stopped

networks:
  default:
    name: voice-interview-network
    driver: bridge

volumes:
  logs: 