version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-interview-app
    ports:
      - "3000:3000"
      - "9999:9999"
    environment:
      - PORT=9999
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    name: voice-interview-network
    driver: bridge

volumes:
  logs: 