version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:9999
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
      - PORT=9999
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongodb_data: 