services:
  # Backend service
  - type: web
    plan: free
    name: voice-interview-backend
    runtime: docker
    repo: https://github.com/vaibhav-chaudhari6696/AI-Interview-Voice-Assistant
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: PORT
        value: 9999
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        fromService:
          name: voice-interview-frontend
          type: web
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

  # Frontend service
  - type: web
    plan: free
    name: voice-interview-frontend
    runtime: docker
    repo: https://github.com/vaibhav-chaudhari6696/AI-Interview-Voice-Assistant
    dockerfilePath: ./Dockerfile.frontend
    envVars:
      - key: PORT
        value: 3000
      - key: REACT_APP_API_URL
        fromService:
          name: voice-interview-backend
          type: web
          property: connectionString
    healthCheckPath: /
    autoDeploy: true 